name = "LightGBM"
uuid = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
version = "0.7.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LightGBM_jll = "0e4427ef-1ff7-5cd7-8faa-8ff0877bb2ec"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LightGBM_jll = "3"
MLJModelInterface = "^0.3.6,^0.4,^1.0"
julia = "1.6"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "Random", "Test"]
